[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "numcosmo_I"
version = "0.1.0"
description = "Bayesian analysis for numerical cosmology - 2026"
dependencies = [
    "numpy",
    "scipy",
    "pyyaml"
]

[project.optional-dependencies]
dev = ["pytest"]

[tool.setuptools.packages.find]
where = ["."]
